config/routes.rb
Rails.application.routes.draw do
  resources :linkers

  root 'home#index'
  
  get "resume_json" => "home#resume_json"

end

app/models/linker.rb
class Linker < ActiveRecord::Base

  validates_presence_of :original_link
  before_save :generate_hash
  SALT = "any_long_random_string_will_do"
  
  
  def generate_hash
    self.hashing = Gibberish::MD5(SALT + self.original_link) if !self.original_link.blank?
  end

  def full_link
    if self.original_link[0..3] != "http"
      return "http://" + self.original_link
    else
      return self.original_link
    end
  end
  
end

app/models/tic_tac_toe.rb
class TicTacToe

  WINNING_COMBINATIONS = [
    # Horizontal wins:
    [0, 1, 2], [3, 4, 5], [6, 7, 8],
    # Vertical wins:
    [0, 3, 6], [1, 4, 7], [2, 5, 8],
    # Diagonal wins:
    [0, 4, 8], [2, 4, 6]
  ]

  @@dimension = 3
  def self.start
    player = "X"
    cpu = "O"
    board = Array.new(@@dimension**2)
    puts "Starting game..."
    self.display_board(board)
    puts "do you want to start? (y/n)"
    start_first = gets
    start_first.chomp!
    while ['y','n'].exclude?(start_first)
      puts "invalid input, please choose (y/n)"
      start_first = gets
      start_first.chomp!
    end
    
    while board_winner(board)
    
      if start_first == 'y'
        self.player_move(board)
        start_first = nil
      end
      
      self.cpu_move(board)
      self.display_board(board)
      self.player_move(board)
    end
    self.display_board(board)
    
  end

  def self.display_board(array)
    string = ""
    array.each_with_index do |b, i|
      if b.nil?
        string << (" | " + i.to_s + " | ")
      else
        string << (" | " + b + " | ")
      end
      if (i+1)%@@dimension == 0
        string << "\n"
      end
    end
    puts string  
  end

  def self.valid_move?(array, move)
    if (0..8).include?(move) && array[move].nil?
      return true
    else
      puts "invalid move"
      return false
    end
  end
  
  def self.board_winner(arr)
    x = arr.each_index.select{|i| arr[i] == 'X'}
    o = arr.each_index.select{|i| arr[i] == 'O'}
    
    TicTacToe::WINNING_COMBINATIONS.each do |win|
      if (win - x).blank?
        puts "Winner is X"
        return false
      elsif (win - o).blank?
        puts "Winner is O" 
        return false
      end
    end 
    
    if arr.exclude?(nil)
      puts "DRAW"
      return false
    else
      return true
    end
  end
  
  def self.cpu_move(arr)
    #make cpu smart enough next time, now cpu will just randomly move
    available_move = arr.each_index.select{|i| arr[i] == nil}
    if !available_move.blank?
      arr[available_move.sample] = "O"
    end
  end
  
  def self.player_move(board)
    puts "Please enter 0 to 8" 
    move = gets
    move.chomp!
    while !self.valid_move?(board, move.to_i)
      move = gets
      move.chomp!
    end
    board[move.to_i] = "X"  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :json, only: [:resume_json]

	def index
	end
	
  def resume_json
    hash = {
      :resume => {
        :name => "Mercury Tang", 
        :age => "31", 
        :contact => "016-3177489", 
        :education => "Software Engineering Degree",
        :working_experience => "5 Years"},
      :cv => {
        :technical_skills => "Ruby on Rails, Java, mysql, mongodb, Hardwares assemblies",
        :personal_skills => "Teamwork, Communication, Eager to learn",
        :previous_experience => "Alpha Melon Sdn Bhd (3 years), Share Investor Pte Limited (1 year), MSP System Sdb Bhd (2 years)",
        :website_involved => "mytaman.com, bursamalaysia.com, becon.com.my, shareinvestor.com"}
    }
    render :json => JSON.pretty_generate(hash)#hash.to_json    
  end


end

app/controllers/linkers_controller.rb
class LinkersController < ApplicationController
  before_action :set_linker, only: [:edit, :update, :destroy]

  # GET /linkers
  # GET /linkers.json
  def index
    @linkers = Linker.all
  end

  # GET /linkers/1
  # GET /linkers/1.json
  def show
    @linker = Linker.where(hashing: params[:id]).first
    if !@linker.nil?
      redirect_to @linker.full_link
    else
      redirect_to root_path, notice: "Invalid link"
    end
  end

  # GET /linkers/new
  def new
    @linker = Linker.new
  end

  # GET /linkers/1/edit
  def edit
  end

  # POST /linkers
  # POST /linkers.json
  def create
    @linker = Linker.new(linker_params)

    respond_to do |format|
      if @linker.save
        format.html { redirect_to linkers_path, notice: 'Linker was successfully created.' }
        format.json { render :show, status: :created, location: @linker }
      else
        format.html { render :new }
        format.json { render json: @linker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /linkers/1
  # PATCH/PUT /linkers/1.json
  def update
    respond_to do |format|
      if @linker.update(linker_params)
        format.html { redirect_to linkers_path, notice: 'Linker was successfully updated.' }
        format.json { render :show, status: :ok, location: @linker }
      else
        format.html { render :edit }
        format.json { render json: @linker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linkers/1
  # DELETE /linkers/1.json
  def destroy
    @linker.destroy
    respond_to do |format|
      format.html { redirect_to linkers_url, notice: 'Linker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_linker
      @linker = Linker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def linker_params
      params.require(:linker).permit(:original_link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/linkers_helper.rb
module LinkersHelper
end

app/views/home/index.html.erb
<%= link_to "Resume Json", resume_json_path%></br>
<%= link_to "Linker", linkers_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MindvalleyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/linkers/_form.html.erb
<%= form_for(@linker) do |f| %>
  <% if @linker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@linker.errors.count, "error") %> prohibited this linker from being saved:</h2>

      <ul>
      <% @linker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :original_link %><br>
    <%= f.text_field :original_link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/linkers/edit.html.erb
<h1>Editing Linker</h1>

<%= render 'form' %>

<%= link_to 'Show', @linker %> |
<%= link_to 'Back', linkers_path %>

app/views/linkers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Linkers</h1>

<table>
  <thead>
    <tr>
      <th>Original link</th>
      <th>Hashing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @linkers.each do |linker| %>
      <tr>
        <td><%= linker.original_link %></td>
        <td><%= linker.hashing %></td>
        <td><%= link_to 'Show', linker_path(id: linker.hashing) %></td>
        <td><%= link_to 'Edit', edit_linker_path(linker) %></td>
        <td><%= link_to 'Destroy', linker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Linker', new_linker_path %>

app/views/linkers/new.html.erb
<h1>New Linker</h1>

<%= render 'form' %>

<%= link_to 'Back', linkers_path %>